# In a non-sandbox/demo setup the ConfigMap and Secret
apiVersion: v1
data:
  vsphere.conf: |
    global:
      secretName: cloud-provider-vsphere-credentials
      secretNamespace: kube-system
      thumbprint: '${VSPHERE_TLS_THUMBPRINT}'
    vcenter:
      ${VSPHERE_SERVER}:
        datacenters:
        - '${VSPHERE_DATACENTER}'
        secretName: cloud-provider-vsphere-credentials
        secretNamespace: kube-system
        server: '${VSPHERE_SERVER}'
        thumbprint: '${VSPHERE_TLS_THUMBPRINT}'
kind: ConfigMap
metadata:
  name: vsphere-cloud-config
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-provider-vsphere-credentials
  namespace: kube-system
stringData:
  ${VSPHERE_SERVER}.password: ${VSPHERE_PASSWORD}
  ${VSPHERE_SERVER}.username: ${VSPHERE_USERNAME}
type: Opaque
