apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: ${CLUSTER_NAME}-controlplane
spec:
  start: 172.16.42.223
  end: 172.16.42.227
  prefix: 24
  gateway: 172.16.42.1
---
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: ${CLUSTER_NAME}-worker
spec:
  start: 172.16.42.246
  end: 172.16.42.252
  prefix: 24
  gateway: 172.16.42.1