apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: ${CLUSTER_NAME}-controlplane
spec:
  start: 192.168.0.230
  end: 192.168.0.234
  prefix: 24
  gateway: 192.168.0.1
---
apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: InClusterIPPool
metadata:
  name: ${CLUSTER_NAME}-worker
spec:
  start: 192.168.0.236
  end: 192.168.0.250
  prefix: 24
  gateway: 192.168.0.1