---
## Cluster configs

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.240.0.0/16"]
    services:
      cidrBlocks: ["10.96.128.0/12"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    kind: TalosControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: ${CLUSTER_NAME}-controlplane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereCluster
metadata:
  name: ${CLUSTER_NAME}
  labels:
    cluster.x-k8s.io/ip-pool-name: ${CLUSTER_NAME}-controlplane
spec:
  controlPlaneEndpoint:
    host: ${CONTROL_PLANE_ENDPOINT}
    port: 6443
  identityRef:
    kind: Secret
    name: ${CLUSTER_NAME}
  server: ${VSPHERE_SERVER}
  thumbprint: ${VSPHERE_TLS_THUMBPRINT}
---
## Control plane configs
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: ${CLUSTER_NAME}-controlplane
spec:
  version: v${KUBERNETES_VERSION}
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  infrastructureTemplate:
    kind: VSphereMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: ${CLUSTER_NAME}-controlplane-${VSPHERE_CONTROL_PLANE_TEMPLATE}-${CONTROL_PLANE_REVISION}
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: ${TALOS_VERSION}
      configPatches:
      - op: replace
        path: /machine/install
        value:
          extraKernelArgs:
          - talos.platform=vmware
      - op: add
        path: /cluster/apiServer/extraArgs
        value:
          allow-privileged: "true"
          anonymous-auth: "True"
          authentication-token-webhook-version: authentication.k8s.io/v1beta1
          authorization-mode: Node,RBAC
          bind-address: "0.0.0.0"
          kubelet-preferred-address-types: InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP
          profiling: "False"
          request-timeout: 1m0s
      - op: replace
        path: /cluster/apiServer/certSANs
        value:
          - ${CONTROL_PLANE_ENDPOINT}
      - op: replace
        path: /cluster/apiServer/admissionControl
        value:
          - name: PodSecurity
            configuration:
              apiVersion: pod-security.admission.config.k8s.io/v1alpha1
              defaults:
                  audit: restricted
                  audit-version: latest
                  enforce: baseline
                  enforce-version: latest
                  warn: restricted
                  warn-version: latest
              exemptions:
                namespaces:
                  - kube-system
                  - tigera-operator
                runtimeClasses: []
                usernames: []
              kind: PodSecurityConfiguration
      - op: add
        path: /cluster/network/cni
        value:
          name: custom
          urls:
          - https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/tigera-operator.yaml
          - https://raw.githubusercontent.com/ErikLundJensen/cluster-api-templates/main/vsphere/cni/calico-install.yaml
      # Add taint to new nodes for VMware Cloud Controller (CPI)
      - op: add
        path: /machine/kubelet
        value:
          extraConfig:
            registerWithTaints:
            - key: node.cloudprovider.kubernetes.io/uninitialized
              value: "true"
              effect: NoSchedule
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-controlplane-${VSPHERE_CONTROL_PLANE_TEMPLATE}-${CONTROL_PLANE_REVISION}
  labels:
    cluster.x-k8s.io/ip-pool-name: ${CLUSTER_NAME}-controlplane
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: ${VSPHERE_DATACENTER}
      datastore: ${VSPHERE_CONTROL_PLANE_DATASTORE}
      diskGiB: 10
      additionalDisksGiB:
      - 10
      folder: ${VSPHERE_FOLDER}
      memoryMiB: 8192
      network:
        devices:
        - dhcp4: false
          dhcp6: false
          gateway4: 192.168.0.1
          nameservers:
          - 192.168.0.1
          addressesFromPools:
          - apiGroup: ipam.cluster.x-k8s.io
            kind: InClusterIPPool
            name: ${CLUSTER_NAME}-controlplane
          networkName: ${VSPHERE_NETWORK}
      numCPUs: 2
      os: Linux
      resourcePool: "${VSPHERE_RESOURCE_POOL}"
      server: ${VSPHERE_SERVER}
      storagePolicyName: ""
      template: ${VSPHERE_CONTROL_PLANE_TEMPLATE}
      thumbprint: ${VSPHERE_TLS_THUMBPRINT}
---
## Worker configs
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    nodepool: nodepool-a
  name: ${CLUSTER_NAME}-workers
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
      nodepool: nodepool-a
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
        nodepool: nodepool-a
    spec:
      clusterName: ${CLUSTER_NAME}
      # TODO: a/b in a multi-zone setup
      #failureDomain: ${VSPHERE_ZONE}-a
      version: ${KUBERNETES_VERSION}
      bootstrap:
        configRef:
          name: ${CLUSTER_NAME}-workers
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
      infrastructureRef:
        name: ${CLUSTER_NAME}-workers-${VSPHERE_WORKER_TEMPLATE}-${WORKER_REVISION}
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-workers-${VSPHERE_WORKER_TEMPLATE}-${WORKER_REVISION}
  labels:
    cluster.x-k8s.io/ip-pool-name: ${CLUSTER_NAME}-worker
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: ${VSPHERE_DATACENTER}
      datastore: ${VSPHERE_WORKER_DATASTORE}
      diskGiB: 10
      additionalDisksGiB:
      - 10
      folder: ${VSPHERE_FOLDER}
      memoryMiB: 4096
      network:
        devices:
        - dhcp4: false
          dhcp6: false
          gateway4: 192.168.0.1
          nameservers:
          - 192.168.0.1
          addressesFromPools:
          - apiGroup: ipam.cluster.x-k8s.io
            kind: InClusterIPPool
            name: ${CLUSTER_NAME}-worker
          networkName: ${VSPHERE_NETWORK}
      numCPUs: 2
      os: Linux
      resourcePool: "${VSPHERE_RESOURCE_POOL}"
      server: ${VSPHERE_SERVER}
      storagePolicyName: ""
      template: ${VSPHERE_WORKER_TEMPLATE}
      thumbprint: ${VSPHERE_TLS_THUMBPRINT}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-workers
spec:
  template:
    spec:
      generateType: join
      talosVersion: ${TALOS_VERSION}
      configPatches:
      # Add taint to new nodes for VMware Cloud Controller (CPI)
      - op: add
        path: /machine/kubelet
        value:
          extraConfig:
            registerWithTaints:
            - key: node.cloudprovider.kubernetes.io/uninitialized
              value: "true"
              effect: NoSchedule
---
## Health check for workers
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineHealthCheck
metadata:
  name: ${CLUSTER_NAME}-worker-hc
spec:
  clusterName: ${CLUSTER_NAME}
  maxUnhealthy: 40%
  nodeStartupTimeout: 20m
  selector:
    matchLabels:
      nodepool: nodepool-a
  unhealthyConditions:
    - type: Ready
      status: Unknown
      timeout: 300s
    - type: Ready
      status: "False"
      timeout: 300s
